name: Publish Docker images

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Publish on DockerHub."
        required: true
      es_version:
        description: "Elasticsearch version."
        type: string
        required: false
        default: 6.5.3
      force_release:
        description: "Force release even if version already exists."
        type: boolean
        required: false
        default: false

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORGANIZATION_NAME: agallea
      DOCKER_REPOSITORY_NAME: elasticsearch-6.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if specified version is already pushed
        run: |
          EXISTS=$(docker manifest inspect $DOCKER_ORGANIZATION_NAME/$DOCKER_REPOSITORY_NAME:${{ github.event.inputs.version }} > /dev/null; echo $?)
          echo $EXISTS
          if [[ ${EXISTS} -eq 0 ]]; then
              echo 'The specified version has been already released to DockerHub.'
              if [[ ${{ github.event.inputs.force_release }} = true ]]; then
                echo 'version exists, forcing release!'
              else
                echo 'version exists, stopping release!'
                exit 1
              fi
          else
              echo 'release new version to DockerHub.'
          fi

      - name: Download memgraph binary
        run: |
          curl -L https://corretto.aws/downloads/latest/amazon-corretto-8-aarch64-linux-jdk.deb > amazon-jdk-arm64.deb
          curl -L https://corretto.aws/downloads/latest/amazon-corretto-8-x64-linux-jdk.deb > amazon-jdk-amd64.deb

      - name: Build & push docker images
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg ES_VERSION=${{ github.event.inputs.es_version }} \
          --tag $DOCKER_ORGANIZATION_NAME/$DOCKER_REPOSITORY_NAME:${{ github.event.inputs.version }} \
          --tag $DOCKER_ORGANIZATION_NAME/$DOCKER_REPOSITORY_NAME:latest \
          --file Dockerfile \
          --push .
